POLICY_ERRORS = {
    "POLICY_DENIED",
    "PAIRING_REQUIRED",
    "APPROVAL_PENDING",
    "APPROVAL_DENIED",
}

GATEWAY_ERRORS = {
    "GATEWAY_INTERNAL_ERROR",
    "SESSION_BUSY",
    "REQUEST_ACK_TIMEOUT",
}

CHANNEL_ERRORS = {
    "CHANNEL_AUTH_FAILED",
    "CHANNEL_SEND_FAILED",
    "CHANNEL_EVENT_INVALID",
}

AGENT_ERRORS = {
    "AGENT_TIMEOUT",
    "AGENT_RUN_FAILED",
    "TOOL_EXECUTION_FAILED",
}

ALL_ERROR_CODES = POLICY_ERRORS | GATEWAY_ERRORS | CHANNEL_ERRORS | AGENT_ERRORS
